
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

dist: xenial

addons:
  apt:
    packages:
    - libsdl2-dev # Need sdl2-config. Ubuntu repos only have 2.0.4 available
    - libsdl2-mixer-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libglew-dev

before_install:
  # OSX: Install packages using brew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install llvm sdl2 sdl2_image sdl2_mixer sdl2_ttf glew physfs; fi
  # Linux: Build SDL2 from source to ensure up-to-date 2.0.5 package
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make install-deps-source-sdl2; fi
  # Linux: Build PhysFS from source to ensure up-to-date 3.0.1 package
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -C docker/ compile-physfs && sudo make -C docker/ install-physfs; fi

script:
  # Use -k to continue after errors, ensuring full build log with all errors
  - make -k

notifications:
  email: false
